---
egi_igtf_repo_key_url: "https://dist.eugridpma.info/distribution/igtf/current/GPG-KEY-EUGridPMA-RPM-3"
egi_igtf_repo_url: "http://repository.egi.eu/sw/production/cas/1/current"
egi_igtf_components: "core"
