# file: shibboleth-sp/vars/Debian-buster.yml
#
---

shibboleth_sp_default_version: "3.0"
shibboleth_sp_default_service: shibd
shibboleth_sp_default_conf_path: /etc/shibboleth
shibboleth_sp_default_user: _shibd
shibboleth_sp_default_group: _shibd
