# file: postgresql/vars/Ubuntu-xenial.yml
#
---

postgresql_default_version: "9.5"
postgresql_default_conf_path: "/etc/postgresql/{{ postgresql_version }}"
postgresql_default_data_path: "/var/lib/postgresql/{{ postgresql_version }}"

postgresql_default_service: "postgresql"

postgresql_default_user: "postgres"
postgresql_default_group: "postgres"

postgresql_default_psycopg2_package: "python-psycopg2"
