---


- name: Configure SSP modules
  template:
    src: "{{ item.src_config_path }}"
    dest: "{{ item.dest_config_path }}"
    backup: yes
    force: yes
  become: yes
  with_items: "{{ ssp_mods_extra_enabled }}"
  when: item.src_config_path is defined and item.dest_config_path is defined


- name: Enable SSP modules
  copy:
    content: ""
    dest: "{{ item.path }}/enable"
    force: no
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes
  with_items: "{{ ssp_mods_extra_enabled }}"
  tags:
    - ssp_modules:config:enable


- name: Add extra dictionaries
  template:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
    backup: yes
  become: yes
  with_items: "{{ ssp_mods_extra_dictionaries }}"
  when: item.src_path is defined and item.dest_path is defined
  tags:
    - ssp_modules:config:dict




- name: About Themes
  debug:
    msg:
      - The role also installs Themes, but doesn't produce the CSS files.
      - To produce them, you must install `sass` and follow the installation instructions for each theme.
