---

ssp_repo_url: "git://github.com/simplesamlphp/simplesamlphp.git"
ssp_repo_version: "master"
ssp_path: "/var/simplesamlphp"
# The base path of the URLs to the content of the SimpleSAMPphp www folder.
ssp_baseurlpath: "simplesaml"
# Specify base URL path with the external scheme (protocol) and FQDN if your 
# SimpleSAMLphp installation is hosted behind a reverse proxy.
#ssp_external_baseurlpath: "https://example.com/simplesaml"

ssp_theme: "default"

ssp_session_cookie_name: "SimpleSAMLSessionID"
ssp_authtoken_cookiename: "SimpleSAMLAuthToken"

# Select where to store session information:
# `phpsession` Uses the built-in session management in PHP (default).
# `memcache`   Uses memcached to cache sessions in memory. 
#              Sessions can be distributed and replicated among several
#              memcached servers, enabling both load-balancing and fail-over.
# `sql`        Stores session information in a SQL database (WIP).
#ssp_store_type: "phpsession"

# One or more memcached server groups for storing session information when
# ssp_store_type is set to `memcache`. Every session data item will be mirrored
# in every server group. Each server group is a list of servers. The data items
# will be load-balanced between all servers in each server group.
#ssp_memcache_store_servers:
#  - # Group A
#    - "memcached1.acme.com"
#    - "memcached2.acme.com"
#  - # Group B
#    - "memcached3.acme.com"
#    - "memcached4.acme.com"

#ssp_memcache_store_prefix: "simpleSAMLphp"

ssp_debug: false
ssp_showerrors: false
ssp_errorreporting: true

# Let SSP figure out timezone based on the host machine
ssp_timezone: 'null'
# otherwise set it explicitly, e.g.:
#ssp_timezone: "'Europe/Athens'"

# Available log levels are:
# ERR          No statistics, only errors
# WARNING      No statistics, only warnings/errors
# NOTICE       Statistics and errors
# INFO         Verbose logs
# DEBUG        Full debug logs - not recommended for production
ssp_logging_level: NOTICE

ssp_language_available:
  - "en"
  - "no"
  - "nn"
  - "se"
  - "da"
  - "de"
  - "sv"
  - "fi"
  - "es"
  - "fr"
  - "it"
  - "nl"
  - "lb"
  - "cs"
  - "sl"
  - "lt"
  - "hr"
  - "hu"
  - "pl"
  - "pt"
  - "pt-br"
  - "tr"
  - "ja"
  - "zh"
  - "zh-tw"
  - "ru"
  - "et"
  - "he"
  - "id"
  - "sr"
  - "lv"
  - "ro"
  - "eu"

ssp_language_rtl:
  - "ar"
  - "dv"
  - "fa"
  - "ur"
  - "he"

ssp_language_default: "en"

ssp_authsources_saml:
  # Additional properties: `entity_id`, `idp`.
  - name: default-sp
    # Uncomment to use the discopower module that provides a more user-friendly
    # IdP discovery service compared to the default.
    # Requires `discopower` module in `ssp_mods_enabled` (see below).
    #disco_url: "/{{ ssp_alias }}/module.php/discopower/disco.php"
    # Set to true to generate self-signed SSL certificate for signing requests/
    # response received from/sent to the IdP, as well as for receiving encrypted
    # responses.
    generate_ssl_certificate: false
    # SSL certificate options (ignored when `generate_ssl_certificate` is set to
    # false):
    # You *must* specify the Common Name (CN).
    #ssl_certificate_cn: sp.example.com
    # Algorithm to use when signing any message generated by this SP:
    # - http://www.w3.org/2000/09/xmldsig#rsa-sha1 (default)
    # - http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
    # - http://www.w3.org/2001/04/xmldsig-more#rsa-sha384
    # - http://www.w3.org/2001/04/xmldsig-more#rsa-sha512
    # Note: the use of SHA1 is deprecated and will be disallowed in the future.
    #sign_algorithm: "http://www.w3.org/2000/09/xmldsig#rsa-sha1"
    # Whether authentication requests, logout requests and logout responses
    # sent from this SP should be signed. Default is false.
    #redirect_sign: true
    # Whether logout requests and logout responses received received by
    # this SP should be validated. Default is false.
    #redirect_validate: true
    # Whether to sign authentication requests sent from this SP. Default is 
    # false.
    #sign_authnrequest: true
    # Whether to sign logout messages sent from this SP. Default is false.
    #sign_logout: true
    # SAML V2.0 Metadata Extensions for Login and Discovery
    # UIInfo Items
    # Localised list of names for this entity
    #display_name:
    #  en: Example SP
    # Localised list of descriptions for this entity
    #description:
    #  en: This is an SP used as an example
    # Optional list of logos for this SP
    # - use a transparent background where appropriate
    # - use PNG or GIF (less preferred) images
    # - use HTTPS URLs in order to avoid mixed-content warnings within browsersk
    #logos:
      #- url: "https://example.com/logo-80x60.png"
        # The rendered height of the logo measured in pixels.
        #height: 60
        # The rendered width of the logo measured in pixels.
        #width: 80
        # Optional language code for localised logos.
        #lang: en
      #- url: "https://example.com/logo-50x50.png"
        # The rendered height of the logo measured in pixels.
        #height: 50
        # The rendered width of the logo measured in pixels.
        #width: 50
        # Optional language code for localised logos.
        #lang: en
    # Localised list of URLs where more information about the entity is located
    #information_url:
    #  en: "http://sp.example.com/info/en"
    # Localised list of URLs where the entity's privacy statement is located
    #privacy_statement_url:
    #  en: "http://sp.example.com/privacy/en"
    #entity_attributes:
      #- attribute_name: "http://macedir.org/entity-category"
      #  attribute_values:
      #    - "http://www.geant.net/uri/dataprotection-code-of-conduct/v1"
    # Optional list of contacts in addition to the technical contact configured 
    # through config/config.php
    #contacts:
      # The type of contact. The possible values are `technical`, `support`,
      # `administrative`, `billing`, and `other`.
      #- contact_type: "technical"
        # Optional name of the company for the contact person.
        #company: "ACME"
        # Optional given (first) name of the contact person.
        #given_name: "Jane"
        # Optional surname of the contact person.
        #sur_name: "Doe"
        # Optional `mailto:` URI representing e-mail address of contact person.
        #email_address: "mailto:jane.doe@acme.example.com"
        # Optional telephone number of the contact person.
        #telephone_numbers: "+31(0)12345678"
    # List of attributes this SP requests from the IdP. This list will be added
    # to the generated metadata.
    # The attributes will be added without a `NameFormat` by default. Use the 
    # name_format option to specify the `NameFormat` for the attributes.
    #attributes:
      #name_format: "urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
      #required:
      #  uid: "urn:oid:0.9.2342.19200300.100.1.1"
      #optional:
      #  eduPersonPrincipalName: "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"
      #  eduPersonTargetedID: "urn:oid:1.3.6.1.4.1.5923.1.1.1.10"
      #  commonName: "urn:oid:2.5.4.3"
      #  givenName: "urn:oid:2.5.4.42"
      #  sn: "urn:oid:2.5.4.4"
      #  displayName: "urn:oid:2.16.840.1.113730.3.1.241"
      #  mail: "urn:oid:0.9.2342.19200300.100.1.3"
    # The format of the NameID we request from the IdP. Defaults to the 
    # transient format if unspecified.
    #name_id_policy: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"

# Requires `authfacebook` module in `ssp_mods_enabled`.
#ssp_authsources_facebook:
# - name: facebook
   # Register your Facebook application at http://www.facebook.com/developers
   # App ID or API key (requests with App ID should be faster; https://github.com/facebook/php-sdk/issues/214)
   #api_key: "123456789012345"
   #secret: "1ab23456cdef78g90123h4ij56k789l0"
   # Optional list of additional permissions to request from user
   # See https://developers.facebook.com/docs/facebook-login/permissions
   #req_perms: "email"

# IdP configuration
# Enable SAML 2.0 IdP functionality
ssp_idp_saml20_enabled: false
# Enable Shibboleth 1.3 IdP (SAML 1.1) functionality
ssp_idp_shib13_enabled: false
# Hosted IdP metadata
ssp_idp_hosts: []
  # The entity ID should be a URI. It can also be specified as `__DYNAMIC:1__`,
  # `__DYNAMIC:2__`, ... in which case, the entity ID will be generated 
  # automatically.
  #- entity_id: "__DYNAMIC:1__"
    # The hostname for this IdP. One of the IdPs can also have its `host` set
    #  to `__DEFAULT__`, and that IdP will be used when no other entries in the
    # metadata matches.
    #host: "__DEFAULT__"
    # The Common Name (CN) of the self-signed certificate.
    #ssl_certificate_cn: "idp1.example.com"
    # Algorithm to use when signing any message generated by this IdP:
    # - http://www.w3.org/2000/09/xmldsig#rsa-sha1 (default)
    # - http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
    # - http://www.w3.org/2001/04/xmldsig-more#rsa-sha384
    # - http://www.w3.org/2001/04/xmldsig-more#rsa-sha512
    # Note: the use of SHA1 is deprecated and will be disallowed in the future.
    #sign_algorithm: "http://www.w3.org/2000/09/xmldsig#rsa-sha1"
    # Whether logout requests and logout responses sent from this IdP should be
    # signed. Default is false.
    #redirect_sign: true
    # Whether authentication requests, logout requests and logout responses
    # received/sent from this IdP should be validated. Default is false.
    #redirect_validate: true
    # The authentication source to be used to authenticate users on this IdP.
    #auth: default-sp 
    #contacts:
      # The type of contact. The possible values are `technical`, `support`,
      # `administrative`, `billing`, and `other`.
      #- contact_type: "technical"
        # Optional name of the company for the contact person.
        #company: "ACME"
        # Optional given (first) name of the contact person.
        #given_name: "Jane"
        # Optional surname of the contact person.
        #sur_name: "Doe"
        # Optional `mailto:` URI representing e-mail address of contact person.
        #email_address: "mailto:jane.doe@acme.example.com"
        # Optional telephone number of the contact person.
        #telephone_numbers: "+31(0)12345678"
    # A list with scopes for this IdP. The scopes will be added to the 
    # generated XML metadata. A scope can either be a domain name or a regular
    # expression matching a number of domains.
    #scopes:
    #  - domain1.example.com  
    #  - domain2.example.com  
    # Localised names of the organisation responsible for this IdP.
    #organization_name: 
    #  en: ACME 
    # Localised user-friendly names of the organisation responsible for this
    # IdP.
    #organization_display_name: 
    #  en: ACME
    # Localised URLs of the organisation responsible for this IdP.
    #organization_url: 
    #  en: "https://www.acme.example.com/en"
    # SAML V2.0 Metadata Extensions for Login and Discovery
    # UIInfo Items
    # Localised list of names for this entity
    #display_name:
    #  en: Example IdP
    # Localised list of descriptions for this entity
    #description:
    #  en: This is an IdP used as an example
    # Localised list of URLs where more information about the entity is located
    # Optional list of logos for this IdP
    # - use a transparent background where appropriate
    # - use PNG or GIF (less preferred) images
    # - use HTTPS URLs in order to avoid mixed-content warnings within browsers
    #logos:
      #- url: "https://example.com/logo-80x60.png"
        # The rendered height of the logo measured in pixels.
        #height: 60
        # The rendered width of the logo measured in pixels.
        #width: 80
        # Optional language code for localised logos.
        #lang: en
      #- url: "https://example.com/logo-50x50.png"
        # The rendered height of the logo measured in pixels.
        #height: 50
        # The rendered width of the logo measured in pixels.
        #width: 50
        # Optional language code for localised logos.
        #lang: en
    #information_url:
    #  en: "https://idp1.example.com/info/en"
    # Localised list of URLs where the entity's privacy statement is located
    #privacy_statement_url:
    #  en: "https://idp1.example.com/privacy/en"
    # DiscoHints items
    # List of IPv4 and IPv6 addresses in CIDR notation serviced by or 
    # associated with this IdP.
    #ip_hints:
    #  - "130.59.0.0/16"
    #  - "2001:620::0/96"
    # List of domain names serviced by or associated with this IdP.
    #domain_hints:
    #  - "example.com"
    #  - "www.example.com"
    # List of geographic coordinates serviced by or associated with this IdP.
    # Coordinates are given in the geo URI scheme (RFC5870).
    #geolocation_hints:
    #  - "geo:47.37328,8.531126"
    #  - "geo:19.34343,12.342514"
    #entity_attributes:
      #- attribute_name: "http://macedir.org/entity-category"
      #  attribute_values:
      #    - "http://www.geant.net/uri/dataprotection-code-of-conduct/v1"
    # SAML2-specific options
    # The value to set in the Format field of attribute statements.
    #attributes_name_format: "urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
    # The format of the NameID supported by this IdP. Defaults to the transient
    # format if unspecified.
    #name_id_format: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
    #authproc:
    #  - "10":
          # Maps attribute names to OIDs.
          # Usually combined with SAML:2.0:attrname-format:uri
          #class: "core:AttributeMap"
          #name2oid:
    #  - "90":
          # Requires `consent` in `ssp_mods_enabled`.
          #class: "consent:Consent"
          # The Consent storage backend. Currently only `consent:Cookie` is 
          # supported. This option is optional. If omitted, the user is still
          # asked to consent, but the decision is not saved.
          #store: "consent:Cookie"
          # Optional flag that indicates whether the values of the attributes
          # should be used in calculating the unique hashes that identify the
          # consent. If includeValues is set and the value of an attribute 
          # changes, then the consent becomes invalid. Defaults to false.
          #includeValues: false
          # Optional flag that indicates whether the "Remember" consent 
          # checkbox is checkd by default. Defaults to false.
          #checked: false
          # Indicates whether the "Yes" or "No" button is in fucus by default.
          # This option is optional and can take the value 'yes' or 'no'. 
          # If omitted, neither will recive focus.
          #focus: "yes" | "no"
          # Optional list of attributes whose values should be hidden.
          # Default behaviour is that all attribute values are shown.
          #hiddenAttributes:
  #- entity_id: "__DYNAMIC:2__"
  #    host: "idp2.example.com"

# List of SSP modules to enable
ssp_mods_enabled: []
  #- metarefresh
  #- cron
  #- discopower
  #- consent
  #- authfacebook

# List of SSP modules to disable
ssp_mods_disabled: []

# Configuration options for automated SAML metadata management.
# Requires `metarefresh` and `cron` modules in `ssp_mods_enabled`.  
#
# Global blacklist: Optional list of entityIDs that should be excluded from ALL
# metadata sets.
#ssp_mod_metarefresh_blacklist: 
#  - "https://my.own.domain.com/ssp/saml2/idp/metadata.php"
#
#ssp_mod_metarefresh_sets: 
  #- name: reep
    # Can be `hourly` or `daily`
    #cron: hourly
    # A list of one or more sources that will be included in this metadata set.
    #sources:
      # The source URL where the metadata will be fetched from.
      #- url: "https://reep.refeds.org/entity/69/latest_metadata/"
        # The fingerprint of the certificate used to sign the metadata. 
        # You can omit this option if you don't want to validate the signature
        # on the metadata.
        #validate_fingerprint: "59:1D:4B:46:70:46:3E:ED:A9:1F:CC:81:6D:C0:AF:2A:09:2A:A8:01"
        # Optional list of tags/labels for the entities in the metadata.
        #tags:
        #  - tag1
        #  - tag2
        #authproc:
        #  - "50":
        #      class: "core:ExampleFilter"
        #extra_parameters: |
        #  'foo' => 'bar',
        # Optional list of entityIDs that should be excluded from this src.
        #blacklist:
        #  - "https://black.example.com/idp"
        #  - "https://black.example.com/sp"
        # Optional list of entityIDs that should be included from this src.
        #whitelist:
        #  - "https://white.example.com/idp"
        #  - "https://white.example.com/sp"
    # Maximum cache time in days
    #expire_after: 7
    # Output directory is relative to {{ ssp_path }}/metadata/
    #output_dir: metarefresh-aarc
    # Can be `flatfile` or `serialize`
    #output_format: serialize

# Configuration options for the discopower module that provides a more
# user-friendly IdP discovery service compared to the default.
# Requires `discopower` module in `ssp_mods_enabled`.
#
# List of tags (mapped to tabs) that should be listed in a specific order.
#ssp_mod_discopower_taborder:
#  - tag1
#  - tag2
# Filter list of IdPs by matching the beginning of search keywords
#ssp_mod_discopower_suggest: false
# List of tab/tag translations to add
#ssp_mod_discopower_dictionaries:
#  - tag1:
#      en: "Tab One"
#  - tag2:
#      en: "Tab Two"
